# Generated by Django 5.2.9 on 2025-12-18 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TradingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'My Gold Scalper'", max_length=100
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("DEMO", "Demo Account"), ("LIVE", "Live Account")],
                        default="DEMO",
                        max_length=10,
                    ),
                ),
                (
                    "broker",
                    models.CharField(
                        choices=[
                            ("FXPRO", "FxPro Direct"),
                            ("CTRADER", "FxPro cTrader"),
                            ("MT5", "MetaTrader 5"),
                        ],
                        default="FXPRO",
                        max_length=20,
                    ),
                ),
                (
                    "login_id",
                    models.CharField(max_length=255, verbose_name="Login ID / Email"),
                ),
                ("password", models.CharField(max_length=255)),
                (
                    "server_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'FxPro-Real06'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "equity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Live value including open trades",
                        max_digits=12,
                    ),
                ),
                ("last_sync_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TradePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=20)),
                ("volume", models.DecimalField(decimal_places=2, max_digits=10)),
                ("trade_type", models.CharField(max_length=10)),
                ("open_price", models.DecimalField(decimal_places=5, max_digits=12)),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=12, null=True
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("open_time", models.DateTimeField()),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="trading_bot.tradingaccount",
                    ),
                ),
            ],
        ),
    ]
