# Generated by Django 5.2.9 on 2025-12-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading_bot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tradeposition",
            old_name="current_price",
            new_name="close_price",
        ),
        migrations.AddField(
            model_name="tradeposition",
            name="ai_reasoning",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradeposition",
            name="candle_snapshot",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradeposition",
            name="close_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradeposition",
            name="h1_trend",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tradeposition",
            name="m15_bias",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tradeposition",
            name="sl_pips",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="tradeposition",
            name="tp_pips",
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name="tradeposition",
            name="open_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tradeposition",
            name="symbol",
            field=models.CharField(default="GOLD", max_length=20),
        ),
        migrations.AlterField(
            model_name="tradeposition",
            name="ticket_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="tradeposition",
            name="volume",
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
    ]
