# Generated by Django 5.2.9 on 2025-12-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading_bot", "0002_rename_current_price_tradeposition_close_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeposition",
            name="market_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Exact indicators at entry time (RSI, ATR, BB)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradeposition",
            name="voters",
            field=models.CharField(
                blank=True,
                help_text="List of personas who voted for this trade (e.g. 'WISE, RACER')",
                max_length=255,
                null=True,
            ),
        ),
    ]
