# Generated by Django 5.2.9 on 2026-01-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading_bot", "0003_tradeposition_market_snapshot_tradeposition_voters"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeposition",
            name="sl",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradeposition",
            name="tp",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=12, null=True
            ),
        ),
    ]
